-- roles table
CREATE TABLE roles
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "roles_pk"
            PRIMARY KEY,
    code text NOT NULL
);

CREATE UNIQUE INDEX "roles_code_uindex"
    ON roles (code);

-- users table
CREATE TABLE users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "users_pk"
            PRIMARY KEY,
    username text    NOT NULL,
    password text    NOT NULL,
    email    text,
    role_id  INTEGER NOT NULL
        CONSTRAINT "users_roles_role_id_fk"
            REFERENCES roles
            ON DELETE CASCADE
);

CREATE UNIQUE INDEX "users_email_uindex"
    ON users (email);

CREATE INDEX "users_role_id_uindex"
    ON users (role_id);

CREATE UNIQUE INDEX "users_username_uindex"
    ON users (username);

-- employees table
CREATE TABLE employees
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT "employees_pk"
            PRIMARY KEY,
    first_name  text NOT NULL,
    last_name   text,
    middle_name text,
    birth_date date,
    iin         BIGINT
);

CREATE UNIQUE INDEX "employees_iin_uindex"
    ON employees (iin);